### PR TITLE
Implemented simple use case of JS function

### PR DESCRIPTION
**Pull request by venkatesh920**

### CODE REVIEW

**Comment by venkatesh920** [comment]
Yes, I don't see any issue with the position of the script tag.

Is there any style guideline which recommends otherwise?

**Comment by venkatesh920** [comment]
And yes, setBackgroundImage() sets the css style of the document's background.

**Comment by venkatesh920** [comment]
https://stackoverflow.com/questions/436411/where-is-the-best-place-to-put-script-tags-in-html-markup

Will move script tag to the end of body.

**Comment by abhiskk** [comment]
Don't move it to the end of body, move it to head with the async option, eg:
script type="text/javascript" src="path/to/script1.js" async

**Comment by venkatesh920** [comment]
Ok.

**Pull request merged**
